export default function TermsPage({ onNavigate }) {
  return (
    <div className="legal-page">
      <div className="legal-hero">
        <p className="legal-eyebrow">Legal</p>
        <h1 className="legal-title">Terms of Service</h1>
        <p className="legal-subtitle">Last updated: June 2026</p>
      </div>

      <div className="legal-content">
        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Code a Cuisine ("the Service"), you agree to be bound by these
            Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>
            Code a Cuisine is an AI-powered recipe generator that creates personalised recipes
            based on the ingredients and preferences you provide. The Service is intended for
            personal, non-commercial use.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. Use of the Service</h2>
          <p>You agree to use the Service only for lawful purposes and in a manner that does not
          infringe the rights of others. You may not:</p>
          <ul>
            <li>Use the Service to generate content that is harmful, misleading, or unlawful.</li>
            <li>Attempt to reverse-engineer, scrape, or otherwise extract data from the Service in bulk.</li>
            <li>Use the Service in any way that could damage, disable, or overburden our infrastructure.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>4. AI-Generated Content</h2>
          <p>
            Recipes generated by Code a Cuisine are produced by artificial intelligence and are
            provided for informational purposes only. We do not guarantee the accuracy, safety, or
            suitability of any recipe for your specific dietary needs or health conditions. Always
            verify ingredient quantities, cooking temperatures, and allergen information independently.
            Consult a medical professional or registered dietitian before making significant dietary changes.
          </p>
        </section>

        <section className="legal-section">
          <h2>5. Nutritional Information</h2>
          <p>
            Calorie, protein, carbohydrate, and fat estimates provided in recipes are approximate
            and calculated by AI. They should not be used as a substitute for professional nutritional
            advice. Actual values may vary depending on specific ingredient brands and preparation methods.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. Intellectual Property</h2>
          <p>
            The Code a Cuisine name, logo, and interface design are our intellectual property. Recipes
            generated through the Service are freely yours to use for personal purposes. We do not
            claim ownership of the recipes you generate.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" without warranties of any kind, express or implied. We do
            not warrant that the Service will be uninterrupted, error-free, or that generated recipes
            will meet your expectations.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, Code a Cuisine shall not be liable for any
            indirect, incidental, or consequential damages arising from your use of the Service or
            any recipes generated through it.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Changes to These Terms</h2>
          <p>
            We reserve the right to update these Terms at any time. Continued use of the Service
            after changes are posted constitutes your acceptance of the revised Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>10. Contact</h2>
          <p>
            If you have questions about these Terms, please reach out to us at{' '}
            <a href="mailto:hello@codeacuisine.com">hello@codeacuisine.com</a>.
          </p>
        </section>
      </div>

      <div className="legal-footer">
        <button className="btn btn--ghost" onClick={() => onNavigate('generator')}>
          ← Back to Generator
        </button>
      </div>
    </div>
  );
}
